#!/bin/bash

usage(){
  echo usage: osx-set-bg BACKGROUND_IMAGE
}

if [[ $# -lt 1 ]]; then usage; exit 0; fi

BACKGROUND_IMAGE=$1

osascript -e "
    tell application \"Finder\"
    set desktop picture to POSIX file \"${BACKGROUND_IMAGE}\"
    end tell
    "