#!/bin/bash

usage(){
  echo usage: rotate LAUNCHD_NAME SYSLOG_CONF
}

if [[ $# -lt 2 ]]; then usage; exit 0; fi
    
LAUNCHD_NAME=$1
SYSLOG_CONF=$2

launchctl stop $LAUNCHD_NAME
newsyslog -r -f $SYSLOG_CONF
launchctl start $LAUNCHD_NAME
